import { describe, it, expect, beforeAll, beforeEach, afterAll } from 'vitest';
import { readFileSync, readdirSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, resolve } from 'path';

import connection from '../src/database/index.js';

import {
  setupTestData,
  teardownTestData,
  ORDINARY_STUDENT,
  ORPHAN_STAFF,
} from './helpers/db.js';

const {
  ClassAllocation,
  StaffUnit,
  Student,
  StudentClass,
  Subject,
  Unit,
  UnitClass,
} = connection.models;

// Sem `id` no init o Sequelize insere um implícito, que ele mesmo descarta ao
// promover o par de FKs a chave primária quando o model vira `through`. A marca
// `_autoGenerated` separa o implícito do declarado; só o declarado sobrevive.
const SURROGATE_JUNCTIONS = [
  ['StudentClass', StudentClass],
  ['ClassAllocation', ClassAllocation],
  ['StaffUnit', StaffUnit],
];

const __dirname = dirname(fileURLToPath(import.meta.url));
const modelsDir = resolve(__dirname, '..', 'src', 'models');

const HOST_UNIT = {
  id: 9704,
  name: 'Fixture Junction Unit',
  cnpj: '97040000000100',
  email: 'unit9704@test.local',
  phone: '1130007704',
  status: 'active',
};

const HOST_CLASS = {
  id: 9804,
  unit_id: HOST_UNIT.id,
  name: '6D-FIX',
  grade_level: '6th Grade',
  room_number: 'R104',
  shift: 'morning',
  school_year: '2026',
  max_students: 30,
  status: 'active',
};

const HOST_SUBJECT = {
  id: 9601,
  name: 'Fixture Subject',
  code: 'FIX601',
  status: 'active',
};

async function destroyFixtures() {
  await StudentClass.destroy({ where: { unit_class_id: HOST_CLASS.id } });
  await ClassAllocation.destroy({ where: { unit_class_id: HOST_CLASS.id } });
  await UnitClass.destroy({ where: { id: HOST_CLASS.id } });
  await Unit.destroy({ where: { id: HOST_UNIT.id } });
  await Subject.destroy({ where: { id: HOST_SUBJECT.id } });
}

beforeAll(async () => {
  await setupTestData();
  await destroyFixtures();
  await Unit.create(HOST_UNIT);
  await UnitClass.create(HOST_CLASS);
  await Subject.create(HOST_SUBJECT);
});

beforeEach(async () => {
  await StudentClass.destroy({ where: { unit_class_id: HOST_CLASS.id } });
  await ClassAllocation.destroy({ where: { unit_class_id: HOST_CLASS.id } });
});

afterAll(async () => {
  await destroyFixtures();
  await teardownTestData();
  await connection.close();
});

describe('junção — a chave primária é a surrogate declarada, não o par de FKs', () => {
  it.each(SURROGATE_JUNCTIONS)('%s declara o id no init', (_name, model) => {
    const id = model.rawAttributes.id;

    expect(id._autoGenerated).toBeUndefined();
    expect(id.primaryKey).toBe(true);
    expect(id.autoIncrement).toBe(true);
  });

  it.each(SURROGATE_JUNCTIONS)(
    '%s tem o id como única chave primária',
    (_name, model) => {
      expect(model.primaryKeyAttributes).toEqual(['id']);
      expect(model.primaryKeyAttribute).toBe('id');
    },
  );

  it('StudentClass.findByPk localiza a linha pela surrogate', async () => {
    const created = await StudentClass.create({
      student_id: ORDINARY_STUDENT.id,
      unit_class_id: HOST_CLASS.id,
    });

    expect(typeof created.id).toBe('number');

    const found = await StudentClass.findByPk(created.id);
    expect(found).not.toBeNull();
    expect(found.student_id).toBe(ORDINARY_STUDENT.id);
    expect(found.unit_class_id).toBe(HOST_CLASS.id);
  });

  it('ClassAllocation.findByPk localiza a linha pela surrogate', async () => {
    const created = await ClassAllocation.create({
      staff_id: ORPHAN_STAFF.id,
      unit_class_id: HOST_CLASS.id,
      subject_id: HOST_SUBJECT.id,
    });

    expect(typeof created.id).toBe('number');

    const found = await ClassAllocation.findByPk(created.id);
    expect(found).not.toBeNull();
    expect(found.staff_id).toBe(ORPHAN_STAFF.id);
    expect(found.subject_id).toBe(HOST_SUBJECT.id);
  });
});

describe('junção — o through aponta para o model registrado', () => {
  it('UnitClass.students atravessa o próprio StudentClass', () => {
    const association = UnitClass.associations.students;

    expect(association.through.model).toBe(StudentClass);
    expect(association.through.unique).toBe(false);
  });

  it('nenhum model anônimo é registrado sobre student_classes', () => {
    const owners = Object.values(connection.models).filter(
      (model) => model.tableName === 'student_classes',
    );

    expect(owners).toEqual([StudentClass]);
  });

  it('nenhum model declara through por string', () => {
    const offenders = readdirSync(modelsDir)
      .filter((file) => file.endsWith('.js'))
      .filter((file) =>
        /through:\s*['"]/.test(readFileSync(resolve(modelsDir, file), 'utf8')),
      );

    expect(offenders).toEqual([]);
  });
});

describe('junção — o vínculo criado pelo alias herda os defaults do model', () => {
  it('addStudent insere sem informar as colunas obrigatórias', async () => {
    const unitClass = await UnitClass.findByPk(HOST_CLASS.id);
    const student = await Student.findByPk(ORDINARY_STUDENT.id);

    await unitClass.addStudent(student);

    const link = await StudentClass.findOne({
      where: {
        student_id: ORDINARY_STUDENT.id,
        unit_class_id: HOST_CLASS.id,
      },
    });

    expect(link).not.toBeNull();
    expect(link.id).toBeGreaterThan(0);
    expect(link.enrollment_date).not.toBeNull();
    expect(link.enrollment_status).toBe('active');
    expect(link.status).toBe('active');
  });
});
