FROM node:22 AS build-stage
WORKDIR /usr/src/app

ARG REACT_APP_API_URL
ARG PUBLIC_URL=/
ENV REACT_APP_API_URL=$REACT_APP_API_URL
ENV PUBLIC_URL=$PUBLIC_URL

COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM caddy:2-alpine
COPY --from=build-stage /usr/src/app/build /srv
COPY Caddyfile /etc/caddy/Caddyfile

EXPOSE 80 443
