FROM node:22-slim@sha256:d9f850096136edbc402debdd8729579a288aac64574ada0ff4db26b6ae58b0b2

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm ci

COPY . .

RUN mkdir -p uploads/images && chown -R node:node /usr/src/app

USER node

EXPOSE 3001

CMD ["node", "src/server.js"]
