export const CREATE_GUARDIAN_REQUEST = 'CREATE_GUARDIAN_REQUEST';
export const CREATE_GUARDIAN_SUCCESS = 'CREATE_GUARDIAN_SUCCESS';
export const CREATE_GUARDIAN_FAILURE = 'CREATE_GUARDIAN_FAILURE';

export const GET_GUARDIANS_REQUEST = 'GET_GUARDIANS_REQUEST';
export const GET_GUARDIANS_SUCCESS = 'GET_GUARDIANS_SUCCESS';
export const GET_GUARDIANS_FAILURE = 'GET_GUARDIANS_FAILURE';

export const UPDATE_GUARDIAN_REQUEST = 'UPDATE_GUARDIAN_REQUEST';
export const UPDATE_GUARDIAN_SUCCESS = 'UPDATE_GUARDIAN_SUCCESS';
export const UPDATE_GUARDIAN_FAILURE = 'UPDATE_GUARDIAN_FAILURE';

export const DELETE_GUARDIAN_REQUEST = 'DELETE_GUARDIAN_REQUEST';
export const DELETE_GUARDIAN_SUCCESS = 'DELETE_GUARDIAN_SUCCESS';
export const DELETE_GUARDIAN_FAILURE = 'DELETE_GUARDIAN_FAILURE';

export const GET_CEP_REQUEST = 'GET_CEP_REQUEST';
export const GET_CEP_SUCCESS = 'GET_CEP_SUCCESS';
export const GET_CEP_FAILURE = 'GET_CEP_FAILURE';
