export const CREATE_UNIT_CLASS_REQUEST = 'CREATE_UNIT_CLASS_REQUEST';
export const CREATE_UNIT_CLASS_SUCCESS = 'CREATE_UNIT_CLASS_SUCCESS';
export const CREATE_UNIT_CLASS_FAILURE = 'CREATE_UNIT_CLASS_FAILURE';

export const GET_UNIT_CLASSES_REQUEST = 'GET_UNIT_CLASSES_REQUEST';
export const GET_UNIT_CLASSES_SUCCESS = 'GET_UNIT_CLASSES_SUCCESS';
export const GET_UNIT_CLASSES_FAILURE = 'GET_UNIT_CLASSES_FAILURE';

export const UPDATE_UNIT_CLASS_REQUEST = 'UPDATE_UNIT_CLASS_REQUEST';
export const UPDATE_UNIT_CLASS_SUCCESS = 'UPDATE_UNIT_CLASS_SUCCESS';
export const UPDATE_UNIT_CLASS_FAILURE = 'UPDATE_UNIT_CLASS_FAILURE';

export const DELETE_UNIT_CLASS_REQUEST = 'DELETE_UNIT_CLASS_REQUEST';
export const DELETE_UNIT_CLASS_SUCCESS = 'DELETE_UNIT_CLASS_SUCCESS';
export const DELETE_UNIT_CLASS_FAILURE = 'DELETE_UNIT_CLASS_FAILURE';

export const GET_UNIT_OPTIONS_REQUEST = 'GET_UNIT_OPTIONS_REQUEST';
export const GET_UNIT_OPTIONS_SUCCESS = 'GET_UNIT_OPTIONS_SUCCESS';
export const GET_UNIT_OPTIONS_FAILURE = 'GET_UNIT_OPTIONS_FAILURE';
